foo:
  script:
    - echo Hello
    - echo $CI_COMMIT_BRANCH
  rules:
    - if: '$CI_COMMIT_BRANCH'

bar:
  script:
    - echo Hello
    - echo $CI_COMMIT_BRANCH
  rules:
    - if: '$CI_COMMIT_TAG'

baz:
  script:
    - echo Hello
    - echo $CI_COMMIT_BRANCH
  rules:
    - if: '$NONE'
