spec:
  inputs:
    platform-version:
      description: "Version of the GNOME Platform to install"
    fdsdk-version:
      description: "Version of the FDSDK base"
    llvm-version-1:
      description: "Version of the .Extension.llvm to install"
    llvm-version-2:
      description: "Version of the .Extension.llvm to install"
---
".common:$[[ inputs.platform-version ]]":
  image: "quay.io/buildah/stable:latest"
  variables:
    STORAGE_DRIVER: "vfs"
    BUILDAH_FORMAT: "docker"
    BUILDAH_ISOLATION: "chroot"
  needs: []

".sdk_template:$[[ inputs.platform-version ]]":
  stage: "CI Runtime Images"
  extends: ".common:$[[ inputs.platform-version ]]"
  after_script: []
  # Scheduled pipelines:
  # - Daily for nightly
  # - Monthly for stable
  # TODO: make it a pipeline trigger from gnome-build-meta
  rules:
    - if: '"$[[ inputs.platform-version ]]" == "master"'
      # We trigger sdk image builds when there are changes
      # but we also trigger it on schedules to rebuild only the image
      # withotu rebuilding the base, as there isn't a need.
      needs: ["base-manifest"]
      changes:
        paths:
          - runtime-images/**/*
    # Otherwise allow the image to rebuild without the base,
    # as we are only interested in fetching the flatpak runtime update
    - if: $REBUILD_STABLE != "true" && "$[[ inputs.platform-version ]]" == "master"
      needs: []
    - if: $REBUILD_STABLE == "true" && "$[[ inputs.platform-version ]]" != "master"
      needs: []
  script:
    - bash ./runtime-images/scripts/build-sdk-image.sh "$[[ inputs.platform-version ]]" "$[[ inputs.fdsdk-version ]]" "$[[ inputs.llvm-version-1 ]]" "$[[ inputs.llvm-version-2 ]]"

"gnome:$[[ inputs.platform-version ]]":
  extends: ".sdk_template:$[[ inputs.platform-version ]]"
  variables:
    ARCH: x86_64

"gnome:aarch64:$[[ inputs.platform-version ]]":
  extends: ".sdk_template:$[[ inputs.platform-version ]]"
  tags:
    - aarch64
  variables:
    ARCH: aarch64

"gnome-manifest:$[[ inputs.platform-version ]]":
  stage: "CI Runtime Images"
  extends: ".common:$[[ inputs.platform-version ]]"
  after_script: []
  rules:
    - if: '"$[[ inputs.platform-version ]]" == "master"'
      # We trigger sdk image builds when there are changes
      # but we also trigger it on schedules to rebuild only the image
      # without rebuilding the base, as there isn't a need.
      changes:
        paths:
          - runtime-images/**/*
    - if: $REBUILD_STABLE != "true" && "$[[ inputs.platform-version ]]" == "master"
    - if: $REBUILD_STABLE == "true" && "$[[ inputs.platform-version ]]" != "master"
  needs:
    - job: "gnome:$[[ inputs.platform-version ]]"
      artifacts: false
    - job: "gnome:aarch64:$[[ inputs.platform-version ]]"
      artifacts: false
  script:
    - bash ./runtime-images/scripts/make-manifest.sh "gnome-$[[ inputs.platform-version ]]"
