.base_template:
  image: "quay.io/buildah/stable:latest"
  stage: "gnome-runtime-images"
  needs: []
  # if:
  #   rules:
  #     - changes:
  #         paths:
  #           - "gnome-runtime-images/**/*"
  #           - "templates/build-runtime-images/**/*"
  #           - "flatpak/*"
  #           - "templates/defeault-rules.yml"
  #           - "test-the-templates/flatpak.yml"
  variables:
    # Buildah can't use 'overlay' driver when running inside docker
    STORAGE_DRIVER: "vfs"
    BUILDAH_FORMAT: "docker"
    BUILDAH_ISOLATION: "chroot"
  script:
    - bash ./gnome-runtime-images/scripts/build-image.sh

base:
  extends: ".base_template"
  variables:
    ARCH: x86_64

base:aarch64:
  extends: ".base_template"
  tags:
    - aarch64
    - gnome-build-meta
  variables:
    ARCH: aarch64

base-manifest:
  image: "quay.io/buildah/stable:latest"
  stage: "gnome-runtime-images"
  script:
    - bash ./gnome-runtime-images/scripts/make-manifest.sh "base"
  needs:
    - job: "base"
      artifacts: false
    - job: "base:aarch64"
      artifacts: false

include:
  - local: gnome-runtime-images/build-runtime-images.yml
    inputs:
      platform-version: "master"
      fdsdk-version: "25.08"
      llvm-version-1: "20"
      llvm-version-2: "21"
  - local: gnome-runtime-images/build-runtime-images.yml
    inputs:
      platform-version: "49"
      fdsdk-version: "25.08"
      llvm-version-1: "20"
      llvm-version-2: "21"
  - local: gnome-runtime-images/build-runtime-images.yml
    inputs:
      platform-version: "48"
      fdsdk-version: "24.08"
      llvm-version-1: "18"
      llvm-version-2: "20"
  - local: gnome-runtime-images/build-runtime-images.yml
    inputs:
      platform-version: "47"
      fdsdk-version: "24.08"
      llvm-version-1: "18"
      llvm-version-2: "20"
